autoXMD/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
	path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name="autoXMD/home.html")),
	path('converter/', include('converter.urls')),
	path('sources/',TemplateView.as_view(template_name="autoXMD/sources.html"))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

converter/urls.py
from django.urls import path

from . import views

app_name='converter'

urlpatterns = [
	path('', views.index, name='index'),
	path('initial_read', views.initial_read, name='initial_read'),
	path('instrument_fill',views.instrument_fill,name='instrument_fill')
]

converter/models.py
import os
from django.db import models

class MusicXML(models.Model):
	musicFile = models.FileField(upload_to="xml/",null=True)
	msczFile = models.FileField(upload_to="xml/",null=True,blank=True)
	mmlFile = models.FileField(upload_to="PMD/songs/",null=True,blank=True)
	m2File = models.FileField(upload_to="PMD/songs/",null=True,blank=True)
	flacFile = models.FileField(upload_to="PMD/songs/",null=True,blank=True)
	timestamp = models.DateTimeField(auto_now_add=True)
	instrument_count = models.IntegerField(null=True,blank=True)

class InstrumentName(models.Model):
	name = models.CharField(max_length=100)
	xmlFile = models.ForeignKey('MusicXML',on_delete=models.CASCADE,related_name='instrumentname')

converter/forms.py
from django.forms import ModelForm
from converter.models import *

class MusicXMLForm(ModelForm):
	class Meta:
		model=MusicXML
		fields=['musicFile']

converter/views.py
from django.shortcuts import render
from converter.forms import *
from django.http import JsonResponse
from django.conf import settings
from core.msdos import gen_mxl
from core.mmlmake import read_instrument_metadata
from core.instrument_dicts import get_fm_macro, FM_SCREENNAME, ALL_INSTRUMENTS
from .models import *
import os

ERRORS={
	"badfile":"You did not submit a MusicXML file",
	"long_filename":"Your filename exceeded 8 characters",
	"drums":"Your score includes drums which are <b>not</b> supported",
	"too_many_instruments":"Your score has more than 9 instruments",
	"common_filename":"Someone else has already submitted a file of the same name. Please re-name your file and try again."
}

#helper method: check if filename already exists inside a filefield
def common_filename(filename,typ):
	return filename in [os.path.basename(f).split(".")[0] for f in MusicXML.objects.all().values_list(typ,flat=True)]

#helper method: converts a explicit media path to a relative one
def relative_path(full_path):
	return os.path.relpath(full_path,settings.MEDIA_ROOT)

# VIEWS

def index(request):
	return render(request,"converter/converter_start.html",{'form':MusicXMLForm()})

def initial_read(request):
	if request.method=="POST":
		full_file=request.FILES['musicFile']
		filename=full_file.name.split(".")
		#case 1: fail to meet MS-DOS restriction
		if len(filename[0])>8:
			return JsonResponse({"output":ERRORS["long_filename"]},status=500)
		elif common_filename(filename[0],'musicFile') or common_filename(filename,'msczFile'): #ensures unique filename (so Django doesn't generate random filename/violate 8char limit)
			return JsonResponse({"output":ERRORS["common_filename"]},status=500)

		xmlPackage = MusicXML()
		if filename[1]=="mscz": #convert musescore to musicxml
			xmlPackage.msczFile = full_file
			xmlPackage.save()
			mxl_output = gen_mxl(xmlPackage.msczFile.path)
			if mxl_output[1]==True: #successfull musescore output
				xmlPackage.musicFile.name = relative_path(mxl_output[0])
				xmlPackage.save()
			else: #failed musescore output
				xmlPackage.delete()
				return JsonResponse({"output":mxl_output[0]}, status=500)
		elif filename[1] !="mxl": #didn't actually submit a mxl file
			return JsonResponse({"output":ERRORS["badfile"]}, status=500)
		else: #yes he did, ready to roll
			xmlPackage.musicFile = full_file
			xmlPackage.save()

		#actual processing begins here
		num_instruments,drum_index,unknown_inst,part_names = read_instrument_metadata(xmlPackage.musicFile.path)
		if len(drum_index) !=0 or num_instruments > 9: #return error if problem found
			xmlPackage.delete()
			return JsonResponse({"output":ERRORS["drums"]},status=500) if len(drum_index) !=0 else JsonResponse({"output":ERRORS["too_many_instruments"]},status=500)
		else: 
			for part_name in part_names:
				musicPart = InstrumentName(xmlFile=xmlPackage,name=part_name)
				musicPart.save()
			return JsonResponse({"pk":xmlPackage.pk,"num_instruments":num_instruments})

def instrument_fill(request):
	xmlPackage = MusicXML.objects.get(pk=int(request.GET.get('pk','')))
	table = {}
	for key,value in FM_SCREENNAME.items():
		table[key] = [get_fm_macro(ALL_INSTRUMENTS[key]),value]
	return render(request,"converter/instrument_fill.html",{'table':table,'part_names':xmlPackage.instrumentname.all()})

converter/templates/converter/converter_start.html
{% extends 'autoXMD/home.html' %}
{% load bootstrap4 %}
{% load static %}
{% block title %}MusicXML Converter{% endblock %}
{% block body %}
	<h1>MusicXML <i class="fas fa-arrow-right"></i> PC-98 Converter</h1>
	<p>Submit your MusicXML creations here! The below general process is used to generate PC-98 files:</p>
	<img src = "{% static 'converter/img/diagram.svg' %}" class = "img-fluid mx-auto d-block m-3">
	<p>Additional details about each component is located in the homepage.</p>
	<p>Before you submit, <em>ensure that your submission meets the following restrictions</em>:</p>
	<ul>
		<li><b>Your MusicXML filename shouldn't exceed 8 characters.</b> This is a MS-DOS restriction beyond my control.</li>
		<li><b>Your score shouldn't use any more than 9 instruments</b> as that's the maximum number of instrument channels PMD allows for.</li>
		<li>The following features are <em>not supported</em> and should not be included in your scores:</li>
		<ul>
			<li><b>Unpitched Drums of any kind.</b> Sadly, I was not able to find any features in <code>music21</code> which supports reading drum notes, which rules out PC-98 drum support. <em>Pitched percussion works fine.</em></li>
			<li><b>Multiple repeat endings</b> Similarly, I was not able to find <code>music21</code> inclusion for this feature either.</li>
			<li><b>Measure repeats, specifically <a target = "_blank" href = "https://musescore.org/sites/musescore.org/files/2018-10/measure%20repeat%20symbol.gif">this notation</a>.</b>While specific sheet music software may support this notation, MusicXML does not.</li>
			<li><b>Instrument Changes</b> are a planned upcoming feature. Please don't include them yet.</li>
		</ul>
	</ul>
	<p>When you submit your MusicXML file, <code>autoXMD</code> will analyze it and request appropriate PC-98 instruments. Afterwards you'll get PMD's console output and (hopefully) a <code>.M2</code> file! Consult the console output if something looks wrong.</p>
	<div class = "row">
		<div class = "col-md-3">
			<form method = "POST" id = "MusicXML-submission" class = "text-center">
				{% csrf_token %}
				{% bootstrap_form form %}
				{% buttons %}
					<input type = "submit" value = "Post" class = "btn btn-primary btn-block">
				{% endbuttons %}
			</form>
		</div>
		<div class = "col-md-9 my-auto"><div id = "errors"><div class="alert alert-primary text-center" role="alert"><i class="fas fa-info-circle"></i> Awaiting your score upload</div></div></div>
	</div>
{% endblock %}
{% block js %}
	<script src = "{% static 'converter/js/converter_start.js' %}"></script>
{% endblock %}

converter/templates/converter/instrument_fill.html
{% extends 'autoXMD/home.html' %}
{% load static %}
{% block title %}Instrument Fill In{% endblock %}
{% block body %}
	<h1>Instrument Fill In</h1>
	<p>It is now time to select appropriate PC-98 instruments for your score. There are two types of selectable instruments: FM Synthesis and SSG, of which a maximum of <b>6</b> and <b>3</b> instruments respectively are supported. (My suggestion is to use the SSG instruments as accompaniments since the FM instruments are <em>significantly</em> louder) It is recommended to pair your score's instruments with related PC-98 instruments (e.g. pair bass instruments together) to ensure your score's notes lie within each PC-98 instrument's note range.</p>

	<p>For your convenience, each instrument's PC-98 ID and their "colloquial" name are listed in the below table, as well as a pre-recorded sample. (Credit goes to pedipanol for the instrument selection)</p>

	<div id = "accordion" class = "mb-3">
		<div class="card">
			<div class="card-header text-center" id="headingTwo">
				<h5 class="mb-0">
					<button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
						PC-98 Instrument Reference Table
					</button>
				</h5>
			</div>
			<div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
				<div class="card-body">
					<div class = "table-responsive">
						<table class = "table text-center">
							<thead>
								<tr>
									<th>PC-98 ID</th>
									<th>Colloquial Instrument Name</th>
									<th>Instrument Sample</th>
								</tr>
							</thead>
							<tbody>
								{% for key,value in table.items %}
									<tr>
										<td class = "align-middle">{{ value.0 }}</td>
										<td class = "align-middle">{{ value.1 }}</td>
										{% with 'sound/'|add:key|add:'.mp3' as sound_path %}
											<td><audio controls><source src = "{% static sound_path %}" type = "audio/mp3"></audio></td>
										{% endwith %}
									</tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
	<form method = "POST" id = "instrument-form">
		<div class = "row justify-content-center">
			{% for part in part_names %}
				<div class = "col-md-3 text-center mb-3">
					<div class = "rounded border-left border-right border-bottom instrument-body">
						<p class = "mt-0 instrument-class"><small>TBD</small></p>
						<h2>{{ part.name }}</h2>
						<p>PC-98 Instrument:</p>
						<div class = "mx-3 mb-3">
							<select class = "form-control">
								<option>Choose</option>
								{% for key, value in table.items %}
									<option>{{ value.1 }}</option>
								{% endfor %}
							</select>
						</div>
					</div>
				</div>
			{% endfor %}
		</div>
		<div class = "row mb-3 justify-content-center" id = "errors" style = "display:none;"></div>
		<div class = "row mb-3 justify-content-center">
			<div class = "col-md-2" id = "row-button"><button type="submit" class="btn btn-primary btn-lg btn-block" id = "submit-button" disabled>Live Preview!</button></div>
		</div>
		<div id = "progress-group">
			<div class="progress mb-3">
				<div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuemin="0" aria-valuemax="100"></div>
			</div>
			<p id = "progress-desc"><b>Status</b>: Refining Raw Data...</p>
		</div>
	</form>
{% endblock %}
{% block style %}
<style>
	.instrument-body{
		border-top:1px solid #0A1128;
	}
	.instrument-class{
		background-color:#0A1128;
		color:white;
	}
	.progress{
		height:1rem;
	}
	#progress-group{
		display:none;
	}
	pre{
		white-space:pre-wrap;
		text-align:left;
		background-color:#E8E8E8;
		padding:0.5rem;
		border:1px solid gray;
	}
</style>
{% endblock %}
{% block js %}
	<script src = "{% static 'converter/js/instrument_fill.js' %}"></script>
{% endblock %}

templates/autoXMD/home.html
{% load static %}
<!doctype html>
<html lang="en">
	<head>
		<!-- Required meta tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<title>{% block title %}Home{% endblock %} | autoXMD</title>
		<link rel="icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon" />

		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

		<!-- main css file (will have to djangoify it later) -->
		<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

		<!-- fontawesome -->
		<script src="https://kit.fontawesome.com/ccc0f1dbf3.js"></script>
		{% block style %}{% endblock %}

	</head>
	<body>
		<div class = "jumbotron jumbotron-fluid main-header">
			<div class = "container text-center">
				<h1 class = "display-3">autoXMD</h1>
				<h3 ><small><em>"Ufu, ufu, ufufufufufufufu..."</em></small></h3> 
				<h1>Written by kir12</h1>
				<h2>A Redditaisai 2019 Submission</h2>
				<a href = "/"><img src = "{% static 'img/mascot.png'%}" class = "img-fluid rounded"></a>
				<p class = "pt-3">Figure 1: Smug, Past and Present</p>
				<div class = "row">
					<div class = "col-md-4"><a href = "https://gitlab.com/kir12/autoXMD" target = "_blank"><h3 class = "menu">Gitlab Repo</h3></a></div>
					<div class = "col-md-4"><a href = "{% url 'converter:index' %}"><h3 class = "menu">Converter</h3></a></div>
					<div class = "col-md-4"><a href = "/sources"><h3 class = "menu">Related Links</h3></a></div>
				</div>
			</div>
		</div>
		<div class = "container">
			<!-- TODO: insert space here -->
			{% block body %}
			<div class="alert alert-info text-center" role="alert">
				<i class="fas fa-certificate"></i> <b>New</b>: Resolved a bug concerning converting Muscscore <code>.mscz</code> submissions and X servers
			</div>
			<h1>Yet another small FAQ</h1>
			<ol>
				<h3><li>What is autoXMD?</li></h3>
				{# consider adding PC-9801 and/or YM2608 sound card #}
				<p>autoXMD, without getting into the specifics, is a converter between GUI-based sheet music composing software (e.g. <a href = "https://musescore.com" target = "_blank">Musescore</a>) and a specific type of <em><a href = "https://en.wikipedia.org/wiki/Chiptune" target = "_blank">chiptune</a></em> music, thus allowing users to produce fully authentic chiptune music <em>without knowing any code.</em>. 
				It specializes in producing chiptune music for the the <a href = "https://en.wikipedia.org/wiki/PC-9800_series" target = "_blank">PC-9800 series</a> personal computers (a superpower in the 1980s ~ 1990s Japanese PC market) and in particular for its <a href = "https://en.wikipedia.org/wiki/Yamaha_YM2608" target = "_blank">YM2608</a> sound card.</p>
				<h3><li>Why select a platform as obscure as the PC-98?</li></h3>
				<p>The PC-98's sound card is well known for producing fantastic video game OSTs -- one example is the <a href = "https://en.touhouwiki.net/wiki/Touhou_Project" target = "_blank">Touhou Project</a>'s* earliest games on the PC-98 platform. Thanks to ZUN's (Touhou's maker) musical prowess (<a href = "https://www.youtube.com/watch?v=n1F6P6iavag" target="_blank">example here</a>) and Touhou's large fanbase, <em>many</em> modern songs have been arranged for the PC-98. (Mostly <a href = "https://www.youtube.com/watch?v=lv322JYvig4" target = "_blank">newer Touhou songs</a>, but <a href = "https://www.youtube.com/watch?v=FQxMGwZHs2k" target = "_blank">some not</a>) autoXMD exists as a way to quickly acclimate interested newcomers to the world of PC-98 arranges.</p>
				<p> And yes, I like Touhou.</p>
				<h3><li>How does autoXMD function?</li></h3>
				<p>The exact technical details are located inside <code>README.md</code> on autoXMD's repository, but the general process is</p>
				<ol class = "mb-3">
					<li>A user submits a sheet music file, preferrably a MusicXML file, (The universal sheet music filetype) and selects appropriate PC-98 instruments.</li>
					<li>autoXMD then reads through the sheet music file and generates an equivalent PC-98 source file, otherwise known as a <code>.mml</code> file.</li>
					<li>The <code>.mml</code> file is passed into the <a href = "https://battleofthebits.org/lyceum/View/Professional+Music+Driver+%28PMD%29/" target = "_blank">Professional Music Driver</a>, a music driver devised by M. Kajihara in the 90s that compiles PC-98 music, and outputs a playable <code>.M2</code> (or <code>.M</code>) file.</li>
					<li>The <code>.M2</code> file is extracted into a more accessible audio format (<code>.wav</code>).</li>
				</ol>
				<p>There are a number of required external dependencies required should you wish to replicate this process locally, which will be listed in <code>README.md</code></p>
				<h3><li>Can autoXMD truly replace knowing MML syntax?</li></h3>
				<p>For typical arrangements, yes. However, autoXMD may not be as effective with more advanced/feature-full pieces, at which point it may help to have some syntax knowledge.
				In short, autoXMD is a <a href = "https://www.youtube.com/watch?v=535Zy_rf4NU" target = "_blank">first step into a larger world</a>.</p>
				<h3><li>How can I contribute/submit a bug report?</li></h3>
				<p>You may do either/both of these things by <a href = "https://gitlab.com/kir12/autoXMD/issues">submitting an issue</a> on autoXMD's repository.</p>
			</ol>
			<p class = "small">*Touhou's deurotagonist -- Marisa Kirisame -- in her PC-98 outfit is showcased as autoXMD's mascot because she is best girl.</p>
			{% endblock %}
		</div>
		<div class = "jumbotron jumbotron-fluid p-2 m-0" id = "footer">
			<div class = "container"><p class = "m-0 text-center"> <b>"Well, perhaps I shall partake of your small spring as well?"</b></p></div>
		</div>
		<!-- Optional JavaScript -->
		<!-- jQuery first, then Popper.js, then Bootstrap JS -->
		<script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
		{% block js %}{% endblock %} {# optional js #}
	</body>
</html>

templates/autoXMD/sources.html
{% extends 'autoXMD/home.html' %}
{% load static %}
{% block title %}Related Links & Credits{% endblock %}
{% block body %}
<h1>Related Links/Credits</h1>
<p>This page lists additional information regarding PC-98 music arranges (and more info regarding autoXMD's stack) for your interest, as well as credits for people who gave me valuable aid for this project.</p>
<div class = "row">
	<div class = "col-md-4">
		<h2 class = "text-center">PC-98 Info</h2>
		<ul>
			<li><a href = "https://battleofthebits.org/lyceum/View/Professional+Music+Driver+%28PMD%29/">PMD's BattleOfTheBits Entry</a></li>
			<li><a href = "http://delmunsoft.com/PMD%20Programming.html">Noyemi K.'s PMD Intro Guide</a></li>
			<li><a href = "https://pigu-a.github.io/pmddocs/pmdmml.htm">(Translated) Professional Music Driver Documentation</a></li>
			<li>mrnauge's YouTube PMD Tutorials (<a href = "https://www.youtube.com/watch?v=xEiCngF5v1A">Part 1</a> and <a href = "https://www.youtube.com/watch?v=FyKxZXTvBvg">Part 2</a>)</li>
			<li><a href = "https://discord.gg/3yX6dxB">PC-98 Discord Link</a></li>
		</ul>
	</div>
	<div class = "col-md-4">
		<h2 class = "text-center">Stack Info</h2>
		<ul>
			<li>Python, <a href = "https://www.djangoproject.com/">Django Web Framework</a>, & <a href = "https://web.mit.edu/music21/"><code>music21</code> Musicology Toolkit</a></li>
			<li><a href = "https://getbootstrap.com/">Bootstrap CSS Framework</a> & <a href = "https://jquery.com/">JQuery Javascript Framework</a></li>
			<li><a href = "http://www.dosemu.org/">Dosemu MS-DOS Emulator</a> & PMD</li>
			<li>gzaffin's PMD music player and audio extractor, <a href = "https://github.com/gzaffin/pmdmini">pmdmini</a></li>
			<li><a href = "https://cloud.google.com/compute/">Google Compute Engine</a> & <a href ="https://www.nginx.com/">Nginx</a></li>
		</ul>
	</div>
	<div class = "col-md-4">
		<h2 class = "text-center">Key Credits</h2>
		<ul>
			<li><a href = "https://www.youtube.com/channel/UCRcvjNhtJBtZoPjXPhtBamA">Pedipanol</a></li>
			<li>🦆2608#6983 (Discord)</li>
			<li><a href = "https://github.com/gzaffin">gzaffin</a></li>
			<li><a href = "https://www.youtube.com/user/ShinkoNet">ShinkoNet</a></li>
		</ul>
	</div>
</div>
<h3 class = "mb-3 text-center">Thank you for visiting!</h3>
{% endblock %}